// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dairy-ui/FieldNotes.tsx": () => import("../components/mockups/dairy-ui/FieldNotes.tsx"),
  "./components/mockups/dairy-ui/Operations.tsx": () => import("../components/mockups/dairy-ui/Operations.tsx"),
  "./components/mockups/dairy-ui/Pastoral.tsx": () => import("../components/mockups/dairy-ui/Pastoral.tsx")
};
